In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

import warnings
warnings.filterwarnings("ignore")

C:\Users\eincr\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Use functions from .py file
%load_ext autoreload
%autoreload 2
import os
import sys
module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

import src.functions as funcs

In [3]:
super_explore =  pd.read_csv('superstore.csv', encoding = 'unicode_escape')

In [4]:
def random_customer_orders(seed, low, high, size):

    
    
    
    rng = np.random.default_rng(1)
    rints = rng.integers(low, high, size)
    return rints
    
    df1 = df[df['Region'] == 'West']
    
    Central_to_West = df1[(df1["Sub-Category"] == 'Paper') | (df1["Sub-Category"] == 'Storage') \
| (df1["Sub-Category"] == 'Tables') | (df1["Sub-Category"] == 'Machines')]
    return Central_to_West





rng = np.random.default_rng(1)
rints = rng.integers(low=0, high=9994, size=200)
rints

array([4729, 5115, 7547, 9498,  348, 1440, 8224, 9480, 2490, 3116, 8685,
       4230, 2730, 8272, 2568, 4089, 6434, 5492,  856,  275, 8650, 7530,
       8373, 5378, 8170, 3295, 4524, 7879, 1238, 3030, 1243, 4532, 9763,
       1339, 3830, 4028, 9033, 2033, 5019, 2621,  198, 7499,  619, 2802,
       4979, 4848, 1168, 9801, 7486, 9610,  920, 7243, 2929, 5409, 9243,
       2767, 7254, 1605, 3223, 9693, 4208, 5157, 2927, 1157, 4243, 6231,
       4553, 7762, 3626, 6126, 7723, 9167, 4270,  395, 7180, 5282, 8715,
       4590, 3678,  623, 4568, 6409, 7696, 8521, 2147, 5925, 8039, 2599,
       3444, 8393, 5812, 5091, 6732, 5105, 9803, 7525,  540, 1478, 5447,
       8191,  689, 6828, 7590, 7866, 8728, 1915, 5549, 8018, 3577, 1912,
       4792,  815, 2198, 8547, 6672, 8607, 8395, 8760, 3103, 4716, 6170,
       2738, 9188,   70, 8377, 6453, 2532, 7194, 4127, 8350, 9976, 2817,
       4697, 2150, 6921, 6389, 8440, 8045, 9763, 9630, 8943, 1504,  421,
       4819, 3448, 8941, 7964, 4224, 5752, 5891, 89

In [5]:
def random_num_of_customer_orders(seed, loc, scale, size1, size2):
    np.random.default_rng(seed)
    rncos = np.random.normal(loc = loc, scale = scale, size = (size1, size2)).tolist()
    rnco = rncos[0]
    rncoi= ([int(a) for a in rnco])
    return rncoi

In [6]:
n = random_num_of_customer_orders(1, 120000, 3000, 1, 100)

In [37]:
o = [1,2,3,4]

In [85]:
def random_customers(lst, low, high):
    customers = []
    for a in lst:
        m = rng.integers(low, high, size=(a))
        customers.append(m)
    return customers

In [89]:
p = random_customers(o, 0, 9994)

In [139]:
a = super_explore.iloc[1:3]
b = super_explore.iloc[2:4]
data = [a, b]
df2 = pd.concat(data)
df2

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   

                                        Product Name     Sales  Quantity  \
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   

   Discount    Profit  
1      0.00  219.5820  
2      0.00    6.8714  
2      0.00    6.8714  
3      0.45 -383.0310  

[4 rows x 21 columns]

In [143]:
def rustomers(a):
    rustomers = []
    for a in p:
        q = super_explore.iloc[a]
        rustomers.append(q)
        df2 = pd.concat(rustomers)
    return df2

In [144]:
rustomers(o)

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
6480    6481  CA-2017-140872    6/3/2017   6/10/2017  Standard Class   
2804    2805  CA-2015-159380   5/12/2015   5/16/2015  Standard Class   
1920    1921  US-2017-111423   8/17/2017   8/19/2017     First Class   
7951    7952  CA-2015-145814  11/19/2015  11/24/2015  Standard Class   
8722    8723  CA-2016-120824   6/12/2016   6/16/2016    Second Class   
5032    5033  CA-2016-155166  12/26/2016    1/2/2017  Standard Class   
7292    7293  CA-2017-109183   12/4/2017   12/9/2017  Standard Class   
696      697  CA-2015-119291   5/14/2015   5/17/2015     First Class   
6062    6063  CA-2015-111780  12/25/2015  12/30/2015    Second Class   
7860    7861  CA-2017-152261    3/2/2017    3/6/2017  Standard Class   

     Customer ID     Customer Name      Segment        Country  \
6480    NR-18550      Nick Radford     Consumer  United States   
2804    CS-12505     Cindy Stewart     Consumer  United States   
1920    EH-13765      Edward Hooks    Corporate  United States   
7951    KD-16345  Katherine Ducich     Consumer  United States   
8722    AW-10930   Arthur Wiediger  Home Office  United States   
5032    BB-11545     Brenda Bowman    Corporate  United States   
7292    LR-16915      Lena Radford     Consumer  United States   
696     JO-15550      Jesus Ocampo  Home Office  United States   
6062    RA-19285      Ralph Arnett     Consumer  United States   
7860    JA-15970      Joseph Airdo     Consumer  United States   

                City  ... Postal Code   Region       Product ID  \
6480  Pembroke Pines  ...       33024    South  OFF-AP-10002287   
2804   San Francisco  ...       94122     West  OFF-PA-10004239   
1920       Watertown  ...       13601     East  FUR-CH-10003981   
7951   New York City  ...       10035     East  OFF-BI-10003196   
8722         Houston  ...       77070  Central  OFF-BI-10001525   
5032        Vineland  ...        8360     East  FUR-CH-10003968   
7292       Nashville  ...       37211    South  TEC-MA-10001856   
696          Chester  ...       19013     East  OFF-EN-10000927   
6062       San Diego  ...       92037     West  TEC-CO-10004202   
7860  Cuyahoga Falls  ...       44221     East  OFF-BI-10002353   

             Category Sub-Category  \
6480  Office Supplies   Appliances   
2804  Office Supplies        Paper   
1920        Furniture       Chairs   
7951  Office Supplies      Binders   
8722  Office Supplies      Binders   
5032        Furniture       Chairs   
7292       Technology     Machines   
696   Office Supplies    Envelopes   
6062       Technology      Copiers   
7860  Office Supplies      Binders   

                                           Product Name     Sales  Quantity  \
6480  Eureka Sanitaire  Multi-Pro Heavy-Duty Upright...    24.472         7   
2804                                         Xerox 1953    25.680         6   
1920  Global Commerce Series Low-Back Swivel/Tilt Ch...   462.564         2   
7951                Accohide Poly Flexible Ring Binders     5.984         2   
8722  Acco Pressboard Covers with Storage Hooks, 14 ...     1.524         2   
5032                           Novimex Turbo Task Chair   212.940         3   
7292                              Okidata C610n Printer   649.000         2   
696       Jet-Pak Recycled Peel 'N' Seal Padded Mailers   200.984         7   
6062  Brother DCP1000 Digital 3 in 1 Multifunction M...  1199.960         5   
7860                            GBC VeloBind Cover Sets    18.528         4   

      Discount    Profit  
6480       0.2    1.8354  
2804       0.0   11.5560  
1920       0.1   97.6524  
7951       0.2    2.2440  
8722       0.8   -2.6670  
5032       0.0   25.5528  
7292       0.5 -272.5800  
696        0.2   62.8075  
6062       0.2  224.9925  
7860       0.7  -12.3520  

[10 rows x 21 columns]

In [ ]:
#Not used as I learned about explode

data2 = [{"Genre":"Animation", "ROI": profit_movies[profit_movies["animation"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["animation"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["animation"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["animation"]==True]['worldwideinmil'].mean()},
         {"Genre":"Adventure", "ROI": profit_movies[profit_movies["adventure"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["adventure"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["adventure"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["adventure"]==True]['worldwideinmil'].mean()},
         {"Genre":"Sci-Fi", "ROI": profit_movies[profit_movies["scifi"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["scifi"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["scifi"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["scifi"]==True]['worldwideinmil'].mean()},
         {"Genre":"Fantasy", "ROI": profit_movies[profit_movies["fantasy"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["fantasy"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["fantasy"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["fantasy"]==True]['worldwideinmil'].mean()},
         {"Genre":"Action", "ROI": profit_movies[profit_movies["action"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["action"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["action"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["action"]==True]['worldwideinmil'].mean()},
         {"Genre":"Family", "ROI": profit_movies[profit_movies["family"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["family"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["family"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["family"]==True]['worldwideinmil'].mean()},
          {"Genre":"Comedy", "ROI": profit_movies[profit_movies["comedy"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["comedy"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["comedy"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["comedy"]==True]['worldwideinmil'].mean()},
          {"Genre":"Music", "ROI": profit_movies[profit_movies["music"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["music"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["music"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["music"]==True]['worldwideinmil'].mean()},
         {"Genre":"Thriller", "ROI": profit_movies[profit_movies["thriller"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["thriller"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["thriller"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["thriller"]==True]['worldwideinmil'].mean()},
         {"Genre":"Sport", "ROI": profit_movies[profit_movies["sport"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["sport"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["sport"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["sport"]==True]['worldwideinmil'].mean()},
         {"Genre":"Horror", "ROI": profit_movies[profit_movies["horror"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["horror"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["horror"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["horror"]==True]['worldwideinmil'].mean()},
         {"Genre":"Mystery", "ROI": profit_movies[profit_movies["mystery"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["mystery"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["mystery"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["mystery"]==True]['worldwideinmil'].mean()},
         {"Genre":"Biography", "ROI": profit_movies[profit_movies["biography"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["biography"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["biography"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["biography"]==True]['worldwideinmil'].mean()},
         {"Genre":"Romance", "ROI": profit_movies[profit_movies["romance"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["romance"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["romance"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["romance"]==True]['worldwideinmil'].mean()},
         {"Genre":"Crime", "ROI": profit_movies[profit_movies["crime"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["crime"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["crime"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["crime"]==True]['worldwideinmil'].mean()},
         {"Genre":"Western", "ROI": roi_movies[roi_movies["western"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["western"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["western"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["western"]==True]['worldwideinmil'].mean(),},
          {"Genre":"Drama", "ROI": profit_movies[profit_movies["drama"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["drama"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["drama"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["drama"]==True]['worldwideinmil'].mean()}, 
         {"Genre":"Documentary", "ROI": profit_movies[profit_movies["documentary"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["documentary"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["documentary"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["documentary"]==True]['worldwideinmil'].mean()},
         {"Genre":"War", "ROI": profit_movies[profit_movies["war"]==True]['roiinmil'].mean(), \
          "Production Budget" : profit_movies[profit_movies["war"]==True]['budgetinmil'].mean(), \
          "Domestic Gross" : profit_movies[profit_movies["war"]==True]['domesticinmil'].mean(), \
          "Worldwide Gross" : profit_movies[profit_movies["war"]==True]['worldwideinmil'].mean()},]
df2 = pd.DataFrame(data2)
df2

In [83]:
customers = []
for a in o:        
    m = rng.integers(0, 9994, size=(a))
    customers.append(m)
print(customers)

[array([6688], dtype=int64), array([8039, 6063], dtype=int64), array([7608, 8306, 7929], dtype=int64), array([9522, 7128, 1291, 7245], dtype=int64)]


In [92]:
p = random_customers(o, 0, 9994)

p

[array([6480], dtype=int64),
 array([2804, 1920], dtype=int64),
 array([7951, 8722, 5032], dtype=int64),
 array([7292,  696, 6062, 7860], dtype=int64)]

In [94]:
for a in p:
    q = super_explore.iloc[a]
    print(q)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
6480    6481  CA-2017-140872   6/3/2017  6/10/2017  Standard Class   

     Customer ID Customer Name   Segment        Country            City  ...  \
6480    NR-18550  Nick Radford  Consumer  United States  Pembroke Pines  ...   

     Postal Code  Region       Product ID         Category Sub-Category  \
6480       33024   South  OFF-AP-10002287  Office Supplies   Appliances   

                                           Product Name   Sales  Quantity  \
6480  Eureka Sanitaire  Multi-Pro Heavy-Duty Upright...  24.472         7   

      Discount  Profit  
6480       0.2  1.8354  

[1 rows x 21 columns]
      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
2804    2805  CA-2015-159380  5/12/2015  5/16/2015  Standard Class   
1920    1921  US-2017-111423  8/17/2017  8/19/2017     First Class   

     Customer ID  Customer Name    Segment        Country           City  ...  \
2804    CS-12505  Cindy Ste

In [62]:
super_explore.iloc[b]

Row ID        Order ID Order Date  Ship Date       Ship Mode  \
2054    2055  CA-2016-136434  12/1/2016  12/7/2016  Standard Class   
4104    4105  US-2017-155999   8/7/2017  8/13/2017  Standard Class   
7901    7902  CA-2017-128363  8/13/2017  8/18/2017  Standard Class   
2567    2568  CA-2017-123967  11/1/2017  11/3/2017    Second Class   

     Customer ID Customer Name   Segment        Country        City  ...  \
2054    RD-19480   Rick Duston  Consumer  United States    Richmond  ...   
4104    JK-15370    Jay Kimmel  Consumer  United States   San Diego  ...   
7901    DC-12850  Dan Campbell  Consumer  United States     Memphis  ...   
2567    SF-20200  Sarah Foster  Consumer  United States  Bellingham  ...   

     Postal Code   Region       Product ID    Category Sub-Category  \
2054       47374  Central  FUR-FU-10001196   Furniture  Furnishings   
4104       92105     West  TEC-PH-10000439  Technology       Phones   
7901       38109    South  FUR-FU-10003268   Furniture  Furnishings   
2567       98226     West  FUR-TA-10003954   Furniture       Tables   

                                           Product Name     Sales  Quantity  \
2054                          DAX Cubicle Frames - 8x10    17.310         3   
4104                           GE DSL Phone Line Filter   159.960         5   
7901  Eldon Radial Chair Mat for Low to Medium Pile ...    31.984         1   
2567                      Hon 94000 Series Round Tables  2665.620         9   

      Discount    Profit  
2054       0.0    5.1930  
4104       0.2   17.9955  
7901       0.2    0.0000  
2567       0.0  239.9058  

[4 rows x 21 columns]

In [54]:
print(random_customers(o, 0, 9994))

[1090 3546 4958 2295]


In [47]:
for a in n: 
    print(rng.integers(low=0, high=9994, size=(a)))

[8021 2551 8035 ...  814  699 1450]
[8232 9039 8456 ...  160 9228 7421]
[2585 5739 2982 ... 3068 6693 2202]
[9624 3902 7335 ... 7102 3198 6980]
[1304 3125 7290 ... 2559 6379 7185]
[3589 3736 9775 ... 4720 7272  310]
[3443 8464 2648 ...  177 9655 1024]
[7536 7540 2963 ... 3843 6472 5715]
[ 359  269 2386 ... 8119 7780 8627]
[6886 6763 5017 ... 7313 5924 5662]
[7516 5245 1231 ... 3194 9183 7349]
[6791 9690 5433 ... 9952 2236 3834]
[  57 1084 4946 ... 9498 5468 4664]
[7300 1874 2218 ...  631 8460  372]
[9002 9120 1500 ... 1606 7291 5970]
[1689 5232  573 ... 5553 9378 5847]
[ 982 7044 3041 ... 5983 7666 8681]
[8289 7958 2086 ... 6694 8587 4977]
[8474 2537 5489 ... 1220 9634 6757]
[6971 2892 3554 ... 8934 1668 3042]
[7348 3662 6104 ... 6009 7746 6816]
[9531 6096 3358 ... 5575 5673 7756]
[9482 1415 9159 ... 4855 7277 3531]
[2460 8479    7 ... 1731 1486 8680]
[1345 9846  763 ...  181  947 3751]
[6720 4130 1814 ... 5946 4413 8016]
[4039 1091 7087 ... 4089 9032 2956]
[4371 6729 8229 ... 8788 806

In [43]:
rng.integers(low=0, high=9994, size=(for a in o: a))

SyntaxError: invalid syntax (Temp/ipykernel_27964/2824816939.py, line 1)

In [7]:
type(n[1])

int

In [24]:
n[1]

124655

In [25]:
(n[a] for a in n)

<generator object <genexpr> at 0x00000246D2591BA0>

I will need to create a function that uses a for loop using the customer order numbers and returns random integers. 

In [8]:
type(n[1])

int

In [19]:
rints = rng.integers(low=0, high=9994, size=(n[1]))

In [20]:
rng.integers(low=0, high=9994, size=(n[1]))

array([7641, 8167, 1079, ...,  565, 6479, 8487], dtype=int64)

In [10]:
 rng.integers(low=0, high = 9000, size=4729)

array([ 790, 8684, 4411, ..., 7449, 3081, 6112], dtype=int64)

In [11]:
super_explore.iloc[rints]

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
5044    5045  CA-2016-158694  11/10/2016  11/13/2016    Second Class   
6534    6535  CA-2014-128209  11/17/2014  11/22/2014  Standard Class   
1592    1593  CA-2015-122826   6/23/2015   6/25/2015    Second Class   
4309    4310  CA-2014-125829   11/4/2014  11/11/2014  Standard Class   
8828    8829  CA-2015-115168    6/5/2015    6/9/2015  Standard Class   
...      ...             ...         ...         ...             ...   
7683    7684  CA-2015-120782   4/28/2015    5/1/2015     First Class   
7934    7935  CA-2017-166093   8/17/2017   8/24/2017  Standard Class   
5253    5254  US-2014-131982    3/7/2014   3/11/2014    Second Class   
9101    9102  CA-2015-163181   11/7/2015  11/12/2015  Standard Class   
1489    1490  CA-2014-136280  11/29/2014   12/6/2014  Standard Class   

     Customer ID    Customer Name      Segment        Country           City  \
5044    AI-10855   Arianne Irving     Consumer  United States    Los Angeles   
6534    GT-14710        Greg Tran     Consumer  United States        Buffalo   
1592    RD-19480      Rick Duston     Consumer  United States        Olympia   
4309    WB-21850    William Brown     Consumer  United States    Los Angeles   
8828    BB-11545    Brenda Bowman    Corporate  United States  Saint Charles   
...          ...              ...          ...            ...            ...   
7683    SD-20485  Shirley Daniels  Home Office  United States        Midland   
7934    RW-19540      Rick Wilson    Corporate  United States      Brentwood   
5253    NP-18685   Nora Pelletier  Home Office  United States     Des Moines   
9101    AB-10105    Adrian Barton     Consumer  United States        Houston   
1489    Co-12640       Corey-Lock     Consumer  United States   Philadelphia   

      ... Postal Code   Region       Product ID         Category Sub-Category  \
5044  ...       90036     West  OFF-PA-10001363  Office Supplies        Paper   
6534  ...       14215     East  OFF-BI-10001359  Office Supplies      Binders   
1592  ...       98502     West  TEC-PH-10004830       Technology       Phones   
4309  ...       90045     West  FUR-TA-10002041        Furniture       Tables   
8828  ...       63301  Central  OFF-PA-10000528  Office Supplies        Paper   
...   ...         ...      ...              ...              ...          ...   
7683  ...       48640  Central  OFF-BI-10003527  Office Supplies      Binders   
7934  ...       94513     West  TEC-PH-10002564       Technology       Phones   
5253  ...       98198     West  OFF-BI-10004224  Office Supplies      Binders   
9101  ...       77041  Central  OFF-AR-10001683  Office Supplies          Art   
1489  ...       19143     East  OFF-LA-10000452  Office Supplies       Labels   

                                           Product Name     Sales  Quantity  \
5044                                         Xerox 1933    61.400         5   
6534         GBC DocuBind TL300 Electric Binding System  2152.776         3   
1592                    Pyle PRT45 Retro Home Telephone   201.568         4   
4309           Bevis Round Conference Table Top, X-Base   573.728         4   
8828                                         Xerox 1981    10.560         2   
...                                                 ...       ...       ...   
7683  Fellowes PB500 Electric Punch Plastic Comb Bin...  3812.970         3   
7934  OtterBox Defender Series Case - Samsung Galaxy S4    71.976         3   
5253               Catalog Binders with Expanding Posts   107.648         2   
9101                                     Lumber Crayons    23.640         3   
1489                                          Avery 488     5.040         2   

      Discount     Profit  
5044       0.0    28.8580  
6534       0.2   726.5619  
1592       0.2    22.6764  
4309       0.2   -64.5444  
8828       0.0     4.7520  
...        ...        ...  
7683       0.0  1906.4850  
7934       0.2     8.9970  
5253  

In [12]:
super_explore.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [13]:
super_explore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [14]:
super_explore['Region'].value_counts()

West       3203
East       2848
Central    2323
South      1620
Name: Region, dtype: int64

In [15]:
super_explore['Sub-Category'].value_counts()

Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: Sub-Category, dtype: int64

In [16]:
funcs.Central_to_West(super_explore)

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
10        11  CA-2014-115812    6/9/2014   6/14/2014  Standard Class   
17        18  CA-2014-167164   5/13/2014   5/15/2014    Second Class   
24        25  CA-2015-106320   9/25/2015   9/30/2015  Standard Class   
42        43  CA-2016-101343   7/17/2016   7/22/2016  Standard Class   
64        65  CA-2015-135545  11/24/2015  11/30/2015  Standard Class   
...      ...             ...         ...         ...             ...   
9944    9945  CA-2015-145415   4/12/2015   4/17/2015    Second Class   
9953    9954  CA-2015-141593  12/14/2015  12/16/2015    Second Class   
9955    9956  CA-2015-141593  12/14/2015  12/16/2015    Second Class   
9975    9976  US-2016-103674   12/6/2016  12/10/2016  Standard Class   
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class   

     Customer ID    Customer Name      Segment        Country         City  \
10      BH-11710  Brosina Hoffman     Consumer  United States  Los Angeles   
17      AG-10270  Alejandro Grove     Consumer  United States  West Jordan   
24      EB-13870      Emily Burns     Consumer  United States         Orem   
42      RA-19885     Ruben Ausman    Corporate  United States  Los Angeles   
64      KM-16720     Kunst Miller     Consumer  United States  Los Angeles   
...          ...              ...          ...            ...          ...   
9944    RD-19660   Robert Dilbeck  Home Office  United States      Seattle   
9953    DB-12970      Darren Budd    Corporate  United States  Los Angeles   
9955    DB-12970      Darren Budd    Corporate  United States  Los Angeles   
9975    AP-10720       Anne Pryor  Home Office  United States  Los Angeles   
9992    DB-13060      Dave Brooks     Consumer  United States   Costa Mesa   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
10    ...       90032    West  FUR-TA-10001539        Furniture       Tables   
17    ...       84084    West  OFF-ST-10000107  Office Supplies      Storage   
24    ...       84057    West  FUR-TA-10000577        Furniture       Tables   
42    ...       90049    West  OFF-ST-10003479  Office Supplies      Storage   
64    ...       90004    West  OFF-PA-10003892  Office Supplies        Paper   
...   ...         ...     ...              ...              ...          ...   
9944  ...       98103    West  OFF-ST-10000419  Office Supplies      Storage   
9953  ...       90045    West  OFF-PA-10004983  Office Supplies        Paper   
9955  ...       90045    West  FUR-TA-10002622        Furniture       Tables   
9975  ...       90032    West  OFF-PA-10000743  Office Supplies        Paper   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   

                                           Product Name     Sales  Quantity  \
10             Chromcraft Rectangular Conference Tables  1706.184         9   
17                           Fellowes Super Stor/Drawer    55.500         2   
24        Bretford CR4500 Series Slim Rectangular Table  1044.630         3   
42     Eldon Base for stackable storage shelf, platinum    77.880         2   
64                                           Xerox 1943   146.730         3   
...                                                 ...       ...       ...   
9944                         Rogers Jumbo File, Granite    40.740         3   
9953                                           Xerox 23     6.480         1   
9955  Bush Andora Conference Table, Maple/Graphite G...   273.568         2   
9975                                         Xerox 1977    13.360         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"    29.600         4   

      Discount    Profit  
10         0.2   85.3092  
17         0.0    9.9900  
24         0.0  240.2649  
42         0.0    3.8940  
64         0.0   68.9631  
...        ...       ...  
9944       0.0    0.4074  
9953       0.0    3.1104  
9955       0.2   10.2588  
9975       0.0    6.4128