In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

import warnings
warnings.filterwarnings("ignore")

C:\Users\eincr\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
# Use functions from .py file
%load_ext autoreload
%autoreload 2
import os
import sys
module_path = os.path.abspath(os.path.join(os.pardir))
if module_path not in sys.path:
    sys.path.append(module_path)

import src.functions as funcs

In [3]:
super_explore =  pd.read_csv('superstore.csv', encoding = 'unicode_escape')

In [10]:
def random_customer_orders(seed, low, high, size):

    
    
    
    rng = np.random.default_rng(1)
    rints = rng.integers(low, high, size)
    return rints
    
    df1 = df[df['Region'] == 'West']
    
    Central_to_West = df1[(df1["Sub-Category"] == 'Paper') | (df1["Sub-Category"] == 'Storage') \
| (df1["Sub-Category"] == 'Tables') | (df1["Sub-Category"] == 'Machines')]
    return Central_to_West





rng = np.random.default_rng(1)
rints = rng.integers(low=0, high=9994, size=200)
rints

array([4729, 5115, 7547, 9498,  348, 1440, 8224, 9480, 2490, 3116, 8685,
       4230, 2730, 8272, 2568, 4089, 6434, 5492,  856,  275, 8650, 7530,
       8373, 5378, 8170, 3295, 4524, 7879, 1238, 3030, 1243, 4532, 9763,
       1339, 3830, 4028, 9033, 2033, 5019, 2621,  198, 7499,  619, 2802,
       4979, 4848, 1168, 9801, 7486, 9610,  920, 7243, 2929, 5409, 9243,
       2767, 7254, 1605, 3223, 9693, 4208, 5157, 2927, 1157, 4243, 6231,
       4553, 7762, 3626, 6126, 7723, 9167, 4270,  395, 7180, 5282, 8715,
       4590, 3678,  623, 4568, 6409, 7696, 8521, 2147, 5925, 8039, 2599,
       3444, 8393, 5812, 5091, 6732, 5105, 9803, 7525,  540, 1478, 5447,
       8191,  689, 6828, 7590, 7866, 8728, 1915, 5549, 8018, 3577, 1912,
       4792,  815, 2198, 8547, 6672, 8607, 8395, 8760, 3103, 4716, 6170,
       2738, 9188,   70, 8377, 6453, 2532, 7194, 4127, 8350, 9976, 2817,
       4697, 2150, 6921, 6389, 8440, 8045, 9763, 9630, 8943, 1504,  421,
       4819, 3448, 8941, 7964, 4224, 5752, 5891, 89

In [104]:
def random_num_of_customer_orders(seed, loc, scale, size1, size2):
    np.random.default_rng(seed)
    rncos = np.random.normal(loc = loc, scale = scale, size = (size1, size2)).tolist()
    rnco = rncos[0]
    rncoi= ([int(a) for a in rnco])
    return rncoi

In [105]:
n = random_num_of_customer_orders(1, 120000, 3000, 1, 100)

In [107]:
type(n[1])

int

I will need to create a function that uses a for loop using the customer order numbers and returns random integers. 

In [69]:
type(n[1])

float

In [122]:
rints = rng.integers(low=0, high=9994, size=(100))

array([[3167, 8919, 4506, ..., 4677, 4661, 3788],
       [6711, 1375, 7683, ..., 3706, 1051,  883],
       [3626, 5959, 8375, ..., 6850,   38, 2512],
       ...,
       [8552, 7390, 8601, ..., 5065,  854, 6184],
       [9976, 7742, 5032, ..., 4289, 7748, 8763],
       [5566, 1899, 6425, ..., 9073, 5856, 4613]], dtype=int64)

In [44]:
 rng.integers(low=0, high = 9000, size=4729)

array([1287, 5058, 1270, ..., 1690, 3010, 8371], dtype=int64)

In [124]:
super_explore.iloc[rints]

ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

In [5]:
super_explore.head()

Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520   
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045   
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335   

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...   
1      Claire Gute   Consumer  United States        Henderson  ...   
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...   
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...   

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases   
1       42420   South  FUR-CH-10000454        Furniture       Chairs   
2       90036    West  OFF-LA-10000240  Office Supplies       Labels   
3       33311   South  FUR-TA-10000577        Furniture       Tables   
4       33311   South  OFF-ST-10000760  Office Supplies      Storage   

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2   
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3   
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2   
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5   
4                     Eldon Fold 'N Roll Cart System   22.3680         2   

   Discount    Profit  
0      0.00   41.9136  
1      0.00  219.5820  
2      0.00    6.8714  
3      0.45 -383.0310  
4      0.20    2.5164  

[5 rows x 21 columns]

In [6]:
super_explore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Row ID         9994 non-null   int64  
 1   Order ID       9994 non-null   object 
 2   Order Date     9994 non-null   object 
 3   Ship Date      9994 non-null   object 
 4   Ship Mode      9994 non-null   object 
 5   Customer ID    9994 non-null   object 
 6   Customer Name  9994 non-null   object 
 7   Segment        9994 non-null   object 
 8   Country        9994 non-null   object 
 9   City           9994 non-null   object 
 10  State          9994 non-null   object 
 11  Postal Code    9994 non-null   int64  
 12  Region         9994 non-null   object 
 13  Product ID     9994 non-null   object 
 14  Category       9994 non-null   object 
 15  Sub-Category   9994 non-null   object 
 16  Product Name   9994 non-null   object 
 17  Sales          9994 non-null   float64
 18  Quantity

In [7]:
super_explore['Region'].value_counts()

West       3203
East       2848
Central    2323
South      1620
Name: Region, dtype: int64

In [8]:
super_explore['Sub-Category'].value_counts()

Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: Sub-Category, dtype: int64

In [9]:
funcs.Central_to_West(super_explore)

Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
10        11  CA-2014-115812    6/9/2014   6/14/2014  Standard Class   
17        18  CA-2014-167164   5/13/2014   5/15/2014    Second Class   
24        25  CA-2015-106320   9/25/2015   9/30/2015  Standard Class   
42        43  CA-2016-101343   7/17/2016   7/22/2016  Standard Class   
64        65  CA-2015-135545  11/24/2015  11/30/2015  Standard Class   
...      ...             ...         ...         ...             ...   
9944    9945  CA-2015-145415   4/12/2015   4/17/2015    Second Class   
9953    9954  CA-2015-141593  12/14/2015  12/16/2015    Second Class   
9955    9956  CA-2015-141593  12/14/2015  12/16/2015    Second Class   
9975    9976  US-2016-103674   12/6/2016  12/10/2016  Standard Class   
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class   

     Customer ID    Customer Name      Segment        Country         City  \
10      BH-11710  Brosina Hoffman     Consumer  United States  Los Angeles   
17      AG-10270  Alejandro Grove     Consumer  United States  West Jordan   
24      EB-13870      Emily Burns     Consumer  United States         Orem   
42      RA-19885     Ruben Ausman    Corporate  United States  Los Angeles   
64      KM-16720     Kunst Miller     Consumer  United States  Los Angeles   
...          ...              ...          ...            ...          ...   
9944    RD-19660   Robert Dilbeck  Home Office  United States      Seattle   
9953    DB-12970      Darren Budd    Corporate  United States  Los Angeles   
9955    DB-12970      Darren Budd    Corporate  United States  Los Angeles   
9975    AP-10720       Anne Pryor  Home Office  United States  Los Angeles   
9992    DB-13060      Dave Brooks     Consumer  United States   Costa Mesa   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
10    ...       90032    West  FUR-TA-10001539        Furniture       Tables   
17    ...       84084    West  OFF-ST-10000107  Office Supplies      Storage   
24    ...       84057    West  FUR-TA-10000577        Furniture       Tables   
42    ...       90049    West  OFF-ST-10003479  Office Supplies      Storage   
64    ...       90004    West  OFF-PA-10003892  Office Supplies        Paper   
...   ...         ...     ...              ...              ...          ...   
9944  ...       98103    West  OFF-ST-10000419  Office Supplies      Storage   
9953  ...       90045    West  OFF-PA-10004983  Office Supplies        Paper   
9955  ...       90045    West  FUR-TA-10002622        Furniture       Tables   
9975  ...       90032    West  OFF-PA-10000743  Office Supplies        Paper   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   

                                           Product Name     Sales  Quantity  \
10             Chromcraft Rectangular Conference Tables  1706.184         9   
17                           Fellowes Super Stor/Drawer    55.500         2   
24        Bretford CR4500 Series Slim Rectangular Table  1044.630         3   
42     Eldon Base for stackable storage shelf, platinum    77.880         2   
64                                           Xerox 1943   146.730         3   
...                                                 ...       ...       ...   
9944                         Rogers Jumbo File, Granite    40.740         3   
9953                                           Xerox 23     6.480         1   
9955  Bush Andora Conference Table, Maple/Graphite G...   273.568         2   
9975                                         Xerox 1977    13.360         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"    29.600         4   

      Discount    Profit  
10         0.2   85.3092  
17         0.0    9.9900  
24         0.0  240.2649  
42         0.0    3.8940  
64         0.0   68.9631  
...        ...       ...  
9944       0.0    0.4074  
9953       0.0    3.1104  
9955       0.2   10.2588  
9975       0.0    6.4128